#!/bin/bash

# Script de déploiement vers Hostinger
# Usage: ./deploy-hostinger.sh

echo "🚀 Déploiement vers Hostinger - Cerfaos"
echo "========================================"
echo ""

# Fichiers à uploader manuellement via FTP
echo "📁 Fichiers à uploader via FTP Hostinger:"
echo ""
echo "1. CSS Mobile Responsive (NOUVEAU):"
echo "   Source: public/css/mobile-responsive-enhanced.css"
echo "   Destination: public_html/public/css/mobile-responsive-enhanced.css"
echo ""
echo "2. Vidéo Mobile Compressée (si pas déjà fait):"
echo "   Source: upload/video/video_092025_mobile.mp4 (22MB)"
echo "   Destination: public_html/upload/video/video_092025_mobile.mp4"
echo ""
echo "3. Vues Laravel modifiées:"
echo "   - resources/views/components/sortie-card.blade.php"
echo "   - resources/views/home/body/home_master.blade.php"
echo "   - resources/views/home/homelayout/slider.blade.php"
echo "   Destination: public_html/resources/views/[chemin identique]"
echo ""
echo "4. SUPPRIMER l'ancien fichier:"
echo "   ❌ public_html/public/css/mobile-no-animations.css"
echo ""
echo "================================"
echo "💡 ALTERNATIVE: Via SSH Hostinger"
echo "================================"
echo ""
echo "Si SSH fonctionne, exécutez:"
echo ""
echo "ssh u729830088@185.224.137.62 << 'ENDSSH'"
echo "cd domains/cerfaos.org/public_html"
echo "git stash"
echo "git pull origin main"
echo "git stash pop"
echo "git checkout --ours .env"
echo "git stash drop"
echo "php artisan config:clear"
echo "php artisan cache:clear"
echo "php artisan view:clear"
echo "ENDSSH"
echo ""
echo "================================"
echo "📋 Checklist après déploiement:"
echo "================================"
echo ""
echo "✓ Vider le cache du navigateur sur mobile"
echo "✓ Tester en mode navigation privée"
echo "✓ Vérifier que le CSS se charge: https://cerfaos.org/css/mobile-responsive-enhanced.css"
echo "✓ Vérifier la vidéo mobile: https://cerfaos.org/upload/video/video_092025_mobile.mp4"
echo ""
